server:
  port: 8082
  servlet:
    context-path: /
spring:
  dubbo:
    application:
      name: service-provider
    base-package: cn.zyc.dubbo.provider.service.impl # dubbo服务发布者所在的包
    registry:
      address: 192.168.3.66 # zookeeper注册中心的地址
      port: 2181       # zookeeper注册中心的端口
      protocol: zookeeper
      register: true
    protocol:
      name: dubbo
      port: 20880
      accesslog: true
    provider:
      retries: 1
      delay: -1
#spring:
#  datasource:
#    name: test
#    url: jdbc:mysql://127.0.0.1:3306/springdb
#    username: root
#    password: root
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#    mybatis:
#      type-aliases-package:  domain